apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-dashboard
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weather-dashboard
  template:
    metadata:
      labels:
        app: weather-dashboard
    spec:
      containers:
      - name: weather-dashboard
        image: your-dockerhub-username/weather-dashboard:latest
        ports:
        - containerPort: 8080
